device: null # if null, it automatically sets the available device. (cuda | mps | cpu)

edge:
  is_mi_based: True # if 0, it generates fully connected edge index.
  n_neighbors: 7
  top_k: 12
  threshold: 0.0
  pruning_ratio: 0.3
  return_edge_attr: False # CAUTION: potential error when set to True
  mi_cached: False

model:
  name: ctmp_gin
  params:
    embedding_dim: 32
    gin_hidden_channel: 96
    gin_1_layers: 2
    gin_hidden_channel_2: 64
    gin_2_layers: 2
    train_eps: True
    los_embedding_dim: 4
    gate_hidden_ch: null # Hidden_dim of GatedFusion, If set to None, it defaults to in_dim, which is gin_hidden_channel * 3
    dropout_p: 0.07776405001461245

train:
  batch_size: 1024
  learning_rate: 0.0008938962898362508 # optimizer learning rate
  epochs: 100
  seed: 1
  binary: True
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
  num_workers: 4
  optimizer: "adamw"
  weight_decay: 2.7801037674268866e-05
  lr_scheduler_patience: 2
  early_stopping_patience: 10
  decision_threshold: 0.5

  ig_label: False # include Neutral labels for Integrated Gradients Method
                  # Must set to False except using Integrated Gradients
  do_preprocess: True
  cv: True
  n_folds: 5
